[project]
name = "http-server-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ruff>=0.16.2",
    "ty>=0.0.71",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["ANN401", "B010", "COM812", "CPY001", "D104", "D107", "D203", "D213", "EM101", "EM102", "TC001", "TC002", "TC003", "TC004", "TC006", "TRY003"]
